# This task is used to merge from one branch to another branch.
# Workspace that is used for this operation. Most of time, this is done on local.
workspace: mergebranch
# The from branch name that is going to be merged to
from_branch: develop
# The to branch name that is going to be merged to
to_branch: master
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the merge branch process due to some environmental issue before.
skip_checkout: false
# You can skip the merge branch step is this has been done in the previous execution.
skip_merge: false
# You can skip the git push after the branch is created. The default is push to the git server.
skip_push: false
# clone and switch to the branch specified in checkout step.
checkout:
  - branch: master
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    - git@github.com:networknt/light-spa-4j.git
    - git@github.com:networknt/light-gateway.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-spring-boot.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/light-example-4j.git
    - git@github.com:networknt/light-example-kotlin.git
    - git@github.com:networknt/light-doc.git
    - git@github.com:networknt/light-bot.git
    - git@github.com:networknt/light-docker.git
    - git@github.com:networknt/light-config-test.git
    - git@github.com:lightapi/light-config-server.git
    - git@github.com:networknt/microservices-framework-benchmark.git
    - git@github.com:networknt/model-config.git
    - git@github.com:networknt/light-config-prod.git
    - git@github.com:networknt/openapi-petstore.git
    - git@github.com:networknt/openapi-market.git
    - git@github.com:networknt/graphql-petstore.git
    - git@github.com:networknt/light-websocket-4j.git
    - git@github.com:networknt/light-genai-4j.git
