# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasedocker_2_0_x
# new upgraded version. This needs to be changed for every release.
version: 2.0.0
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# skip checkout if you know all latest code has been checkout in the previous build
skip_checkout: true
# skip maven build if you know the build has been done already
skip_maven: true
# skip generate change log
skip_change_log: true
# skip check in the generated changelog
skip_checkin: true
# skip upload release_note if it is already done.
skip_release_note: true
# skip docker publish if it is done already.
skip_docker: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  # here we checkout master branch to publish the images. 
  - branch: jdk11
    repository:
    # - git@github.com:networknt/light-proxy.git
    # - git@github.com:networknt/light-router.git
    # - git@github.com:networknt/light-oauth2.git
    # - git@github.com:networknt/light-tokenization.git
    # - git@github.com:networknt/light-portal.git
    # - git@github.com:networknt/light-eventuate-4j.git
    # - git@github.com:networknt/light-tram-4j.git
    # - git@github.com:networknt/light-example-4j.git
    # - git@198.55.49.186:lightapi/tokenization.git
    # - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-docker.git
# maven build
maven:
  # - light-proxy
  # - light-router
  # - light-oauth2
  # - light-tokenization
  # - light-portal
  # - light-eventuate-4j
  # - light-tram-4j
  # - light-example-4j/discovery/api_a/kubernetes
  # - light-example-4j/discovery/api_b/kubernetes
  # - light-example-4j/discovery/api_c/kubernetes
  # - light-example-4j/discovery/api_d/kubernetes
  # - tokenization
  # - light-codegen

# update changelog in master, merge it to develop and publish to github.com
# please note that light-eventuate-4j and light-tram-4j are released in release-maven task.
release:
  # - light-proxy
  # - light-router
  # - light-oauth2
  # - light-tokenization
  # - light-portal
  # - tokenization
  # - light-codegen

# build docker image and push to docker hub
docker:
  # - light-proxy
  # - light-router
  # - light-oauth2/authorize
  # - light-oauth2/client
  # - light-oauth2/code
  # - light-oauth2/key
  # - light-oauth2/refresh-token
  # - light-oauth2/service
  # - light-oauth2/token
  # - light-oauth2/user
  # - light-tokenization
  # - light-portal/hybrid-command
  # - light-portal/hybrid-query
  # - light-example-4j/discovery/api_a/kubernetes
  # - light-example-4j/discovery/api_b/kubernetes
  # - light-example-4j/discovery/api_c/kubernetes
  # - light-example-4j/discovery/api_d/kubernetes
  # need to shutdown docker-compose-integration-test.yml before building the following two images.
  - light-eventuate-4j/eventuate-cdc-server
  - light-tram-4j/tram-cdc-mysql-server
  # - tokenization
  # - light-docker/light-codegen
