path: /
# This is the base used by docker
base: /public
# This is the base that is used for IDE debugging
# base: /home/steve/networknt/light-config-test/light-router/taiji-faucet/view/build
prefix: true
transferMinSize: 10485760
directoryListingEnabled: false
