# Workspace that is used for this operation. Most of time, this is done on local user home.
workspace: regexreplace_2_0_x
# git commit comment for the current task
comment: 'upgrade to snakeyaml to 1.26'
# indicate if you want to skip checkout. yes if you know that all repositories are just checkout
skip_checkout: false
# indicate if you want to skip replace. yes if you have just run the replace first and this time you just want to checkin.
skip_replace: false
# indicate if you want to skip checkin. If you are not comfortable to checkin directly, skip this step and then you can
# skip checkout and replace in second round and only make skip checkin false.
skip_checkin: false
# clone and switch to develop branch or checkout and pull from develop branch. This is to ensure that develop branch for
# each repository is up-to-date for manipulations. Please update skip_checkout to true if you want to bypass this step.
checkout:
  - branch: master
    repository:
    # repositories from github.com
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    - git@github.com:networknt/light-session-4j.git
    - git@github.com:networknt/light-spa-4j.git
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/oauth-kafka.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/light-example-4j.git
    - git@github.com:networknt/light-example-kotlin.git
    - git@github.com:networknt/light-docker.git
    - git@github.com:networknt/light-doc.git
    - git@github.com:networknt/light-config-test.git
    - git@github.com:networknt/light-bot.git
    - git@github.com:networknt/light-config-server.git
    - git@github.com:networknt/microservices-framework-benchmark.git
    - git@github.com:networknt/model-config.git
    - git@github.com:networknt/react-schema-form.git
    - git@github.com:networknt/light-workflow-4j.git
    # - git@github.com:networknt/swagger-bundler.git
    - git@github.com:networknt/openapi-bundler.git
    - git@github.com:networknt/http2client-benchmark.git
    - git@github.com:networknt/json-schema-validator.git
    - git@github.com:networknt/json-schema-validator-perftest.git
    - git@github.com:networknt/microbenchmark.git
    - git@github.com:networknt/react-schema-form-rc-select.git
    - git@github.com:networknt/light-config-prod.git
    - git@github.com:networknt/light-consumer-4j.git
    - git@github.com:networknt/http2client-benchmark.git
    - git@github.com:networknt/microservices-framework-benchmark.git
    - git@github.com:networknt/light-spring-boot.git
    - git@github.com:networknt/light-tram-kafka.git
    - git@github.com:networknt/light-monitor.git
    # - git@github.com:networknt/light-java-hybrid-example.git
    - git@github.com:networknt/light-reference.git
    - git@github.com:networknt/light-kafka.git
    
    # Taiji Block Chain Projects
    - git@github.com:networknt/taiji-blockchain.git
    - git@github.com:taiji-chain/web-client.git
    - git@github.com:taiji-chain/taiji-faucet.git
    - git@198.55.49.186:steve/kafka-chain.git
    - git@198.55.49.186:steve/genesis-block.git
    - git@198.55.49.186:light-chain/chain-reader.git
    - git@198.55.49.186:light-chain/chain-writer.git
    - git@198.55.49.186:light-chain/kyc-reader.git
    - git@198.55.49.186:light-chain/token-reader.git
    # repositories from lightapi.net
    # - git@198.55.49.186:lightapi/tokenization.git
    # Open Banking Projects
    - git@github.com:open-banking/parties.git
    - git@github.com:open-banking/beneficiaries.git
    - git@github.com:open-banking/directDebits.git
    - git@github.com:open-banking/standingOrders.git
    - git@github.com:open-banking/products.git
    - git@github.com:open-banking/statements.git
    - git@github.com:open-banking/scheduledPayments.git
    - git@github.com:open-banking/offers.git
    - git@github.com:open-banking/balances.git
    - git@github.com:open-banking/transactions.git
    - git@github.com:open-banking/accounts.git
# regex replacement from old value to new value during a full text search on certain patterns
# of file names.
replace:
# matched path based on Glob (https://javapapers.com/java/glob-with-java-nio/)
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 0.1.10
#   new_value: 0.1.15

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.9.4
#   new_value: 2.9.5

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.swagger>\d*\.\d*\.\d*</version.swagger>
#   old_value: <version.swagger>1.0.32</version.swagger>
#   new_value: <version.swagger-parser>1.0.34</version.swagger-parser>

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version>[$]\{version.swagger\}</version>
#   old_value: version.swagger}
#   new_value: version.swagger-parser}

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 0.1.15
#   new_value: 0.1.18

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.commons.codec>\d*\.\d*</version.commons.codec>
#   old_value: "1.10"
#   new_value: "1.11"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.commons-text>\d*\.\d*</version.commons-text>
#   old_value: "1.1"
#   new_value: "1.3"


# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jose4j>\d*\.\d*\.\d*</version.jose4j>
#   old_value: "0.6.1"
#   new_value: "0.6.3"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jose4j>\d*\.\d*\.\d*</version.jose4j>
#   old_value: "0.5.2"
#   new_value: "0.6.3"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jose4j>\d*\.\d*\.\d*</version.jose4j>
#   old_value: "0.5.5"
#   new_value: "0.6.3"


# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.0.Final"
#   new_value: "1.4.23.Final"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.10.Final"
#   new_value: "1.4.23.Final"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.20.Final"
#   new_value: "1.4.23.Final"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.11.Final"
#   new_value: "1.4.23.Final"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.18.Final"
#   new_value: "1.4.23.Final"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "1.4.19.Final"
#   new_value: "1.4.23.Final"


# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.snakeyaml>\d*\.\d*</version.snakeyaml>
#   old_value: "1.18"
#   new_value: "1.20"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.caffeine>\d*\.\d*\.\d*</version.caffeine>
#   old_value: "2.5.6"
#   new_value: "2.6.2"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.javamail>\d*\.\d*\.\d*</version.javamail>
#   old_value: "1.6.0"
#   new_value: "1.6.1"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.javamail>\d*\.\d*\.\d*</version.javamail>
#   old_value: "1.4.7"
#   new_value: "1.6.1"


# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.fastscanner>\d*\.\d*\.\d*</version.fastscanner>
#   old_value: "2.7.0"
#   new_value: "2.18.1"
# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.fastscanner>\d*\.\d*\.\d*</version.fastscanner>
#   old_value: "2.0.8"
#   new_value: "2.18.1"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.hikaricp>\d*\.\d*\.\d*</version.hikaricp>
#   old_value: "3.0.0"
#   new_value: "3.1.0"

# - glob: "{**/service.yml,**/service.yml.rocker.raw}"
#   match: com.networknt.server.HandlerProvider
#   old_value: "server"
#   new_value: "handler"

# - glob: "{**/*.java}"
#   match: com.networknt.server.HandlerProvider
#   old_value: "server"
#   new_value: "handler"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 0.1.22
#   new_value: 0.1.23

# - glob: "{**/*.java,**/*.rocker.raw}"
#   match: Http2Client.POOL,
#   old_value: POOL
#   new_value: BUFFER_POOL

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 0.1.25
#   new_value: 0.1.26

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.9.5
#   new_value: 2.9.8

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 0.1.26
#   new_value: 1.0.1

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.11.Final"
#   new_value: "2.0.16.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.8
#   new_value: 1.0.10

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.8
#   new_value: 1.0.10

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.9.8
#   new_value: 2.9.9
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonVersion=\d*\.\d*\.\d*
#   old_value: 2.9.8
#   new_value: 2.9.9

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.13
#   new_value: 1.0.14

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.13
#   new_value: 1.0.14

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.16.Final"
#   new_value: "2.0.21.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.0.16.Final"
#   new_value: "2.0.21.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.15
#   new_value: 1.0.18

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.15
#   new_value: 1.0.18

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.21.Final"
#   new_value: "2.0.23.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.0.21.Final"
#   new_value: "2.0.23.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.19
#   new_value: 1.0.20

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.19
#   new_value: 1.0.20

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.9.9
#   new_value: 2.9.10
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonVersion=\d*\.\d*\.\d*
#   old_value: 2.9.9
#   new_value: 2.9.10

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson-databind>\d*\.\d*\.\d*\.\d*</version.jackson-databind>
#   old_value: 2.9.9.3
#   new_value: 2.9.10
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonDatabindVersion=\d*\.\d*\.\d*\.\d*
#   old_value: 2.9.9.3
#   new_value: 2.9.10

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.22
#   new_value: 1.0.24

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.22
#   new_value: 1.0.24

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.9.10
#   new_value: 2.10.0
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonVersion=\d*\.\d*\.\d*
#   old_value: 2.9.10
#   new_value: 2.10.0

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson-databind>\d*\.\d*\.\d*</version.jackson-databind>
#   old_value: 2.9.10
#   new_value: 2.10.0
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonDatabindVersion=\d*\.\d*\.\d*
#   old_value: 2.9.10
#   new_value: 2.10.0

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.23.Final"
#   new_value: "2.0.28.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.0.23.Final"
#   new_value: "2.0.28.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.json-schema-validator>\d*\.\d*\.\d*</version.json-schema-validator>
#   old_value: 1.0.24
#   new_value: 1.0.29

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jsonSchemaValidatorVersion=\d*\.\d*\.\d*
#   old_value: 1.0.24
#   new_value: 1.0.29

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.30.Final"
#   new_value: "2.0.29.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.0.30.Final"
#   new_value: "2.0.29.Final"

# - glob: "{**/Dockerfile}"
#   match: java.base,java.sql,java.naming,java.desktop,java.xml,jdk.crypto.cryptoki,jdk.unsupported,java.management,java.security.jgss
#   old_value: "jdk.crypto.cryptoki,jdk.unsupported"
#   new_value: "jdk.crypto.cryptoki,jdk.crypto.ec,jdk.unsupported"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.0.29.Final"
#   new_value: "2.1.1.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.0.29.Final"
#   new_value: "2.1.1.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.undertow>\d*\.\d*\.\d*\.Final</version.undertow>
#   old_value: "2.1.1.Final"
#   new_value: "2.1.3.Final"

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: undertowVersion=\d*\.\d*\.\d*\.Final
#   old_value: "2.1.1.Final"
#   new_value: "2.1.3.Final"

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson>\d*\.\d*\.\d*</version.jackson>
#   old_value: 2.10.0
#   new_value: 2.10.4
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonVersion=\d*\.\d*\.\d*
#   old_value: 2.10.0
#   new_value: 2.10.4

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.jackson-databind>\d*\.\d*\.\d*</version.jackson-databind>
#   old_value: 2.10.0
#   new_value: 2.10.4
# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: jacksonDatabindVersion=\d*\.\d*\.\d*
#   old_value: 2.10.0
#   new_value: 2.10.4

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.mysql>\d*\.\d*\.\d*</version.mysql>
#   old_value: 6.0.5
#   new_value: 8.0.16

# - glob: "{**/gradle.properties,**/gradleProperties.rocker.raw}"
#   match: mysqlVersion=\d*\.\d*\.\d*
#   old_value: 6.0.5
#   new_value: 8.0.16

# - glob: "{**/pom.xml,**/pom.xml.rocker.raw}"
#   match: <version.snakeyaml>\d*\.\d*</version.snakeyaml>
#   old_value: "1.20"
#   new_value: "1.26"

- glob: "{**/Dockerfile}"
  match: java.base,java.sql,java.naming,java.desktop,java.xml,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.unsupported,java.management,java.security.jgss
  old_value: "java.security.jgss"
  new_value: "java.security.jgss,java.net.http"
