# This task is used to create a new branch from an existing branch or a tag.
# Workspace that is used for this operation. Most of time, this is done on local.
workspace: createbranch
# The new branch name that is going to be created
branch: 1.6.x
# If the new branch is created from a tag
from_tag: false
# The original tag to create a new branch if from_tag is true.
tag: 1.6.5
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the create branch process due to some environmental issue before.
skip_checkout: false
# You can skip the create branch step is this has been done in the previous execution.
skip_branch: false
# You can skip the git push after the branch is created. The default is push to the git server.
skip_push: false
# clone and switch to the branch specified in checkout step.
checkout:
  - branch: 1.6.x
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    - git@github.com:networknt/light-session-4j.git
    - git@github.com:networknt/light-spa-4j.git
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-consumer-4j.git
    - git@github.com:networknt/light-example-4j.git
    - git@github.com:networknt/light-example-kotlin.git
    - git@github.com:networknt/light-docker.git
    - git@github.com:networknt/light-config-server.git
    - git@github.com:networknt/microservices-framework-benchmark.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/light-workflow-4j.git
    - git@github.com:networknt/http2client-benchmark.git
    - git@github.com:networknt/light-spring-boot.git
