version: "2"
#
# Services
#
services:

  hybrid-command:
      build: ./hybrid-command/
      volumes:
        - ./hybrid-command/cloud/config:/config
        - ./hybrid-command/service:/service
      ports:
        - 8443:8443
      networks:
          - localnet

  hybrid-query:
      build: ./hybrid-query/
      volumes:
        - ./hybrid-query/cloud/config:/config
        - ./hybrid-query/service:/service
      ports:
        - 8442:8442
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true