# This is a configuration file for user-command service
# Indicate if we need to send out the confirmation email during user registration
sendEmail: true
# The event topic for user-command
topic: portal-event
# The host of the server that accepts the email confirmation
cmdHost: https://localhost:8439
# The command path of the server that accepts the email confirmation
cmdPath: /portal/command?cmd=
# The host for password reset. This is usually the login view site.
resetHost: https://dev.signin.lightapi.net
# Admin user email for the bootstrap
admin: stevehu@gmail.com
