
# Singleton service factory configuration/IoC injection
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: jdbc:mysql://198.55.49.187:3306/eventuate?useSSL=false
      username: mysqluser
      password: mysqlpw
      maximumPoolSize: 2
      useServerPrepStmts: true
      cachePrepStmts: true
      cacheCallableStmts: true
      prepStmtCacheSize: 4096
      prepStmtCacheSqlLimit: 2048
- com.networknt.eventuate.jdbc.EventuateJdbcAccess:
  - com.networknt.eventuate.jdbc.EventuateJdbcAccessImpl
- com.networknt.eventuate.common.impl.sync.AggregateCrud:
  - com.networknt.eventuate.server.jdbckafkastore.EventuateLocalAggregateCrud
- com.networknt.eventuate.common.impl.AggregateCrud:
  - com.networknt.eventuate.common.impl.adapters.SyncToAsyncAggregateCrudAdapter
- com.networknt.eventuate.common.impl.AggregateEvents:
  - com.networknt.eventuate.server.jdbckafkastore.EventuateKafkaAggregateSubscriptions
- com.networknt.eventuate.common.SnapshotManager:
  - com.networknt.eventuate.common.SnapshotManagerImpl
- com.networknt.eventuate.common.MissingApplyEventMethodStrategy:
  - com.networknt.eventuate.common.DefaultMissingApplyEventMethodStrategy
- com.networknt.eventuate.common.EventuateAggregateStore:
  - com.networknt.eventuate.common.impl.EventuateAggregateStoreImpl
- com.networknt.eventuate.event.EventHandlerProcessor:
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningVoid
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningVoid
- com.networknt.eventuate.client.SubscriptionsRegistry: com.networknt.eventuate.client.EventuateClientServiceInitializer::subscriptionsRegistry

- net.lightapi.portal.menu.domain.MenuAggregate:
  - net.lightapi.portal.menu.domain.MenuAggregate
- net.lightapi.portal.menu.domain.MenuItemAggregate:
  - net.lightapi.portal.menu.domain.MenuItemAggregate
- net.lightapi.portal.menu.MenuRepository:
  - net.lightapi.portal.menu.MenuRepositoryArangoImpl
- net.lightapi.portal.menu.MenuQueryEventHandler:
  - net.lightapi.portal.menu.MenuQueryEventHandler
- net.lightapi.portal.form.domain.FormAggregate:
  - net.lightapi.portal.form.domain.FormAggregate
- net.lightapi.portal.form.FormRepository:
  - net.lightapi.portal.form.FormRepositoryArangoImpl
- net.lightapi.portal.form.FormQueryEventHandler:
  - net.lightapi.portal.form.FormQueryEventHandler
- net.lightapi.portal.user.UserRepository:
  - net.lightapi.portal.user.UserRepositoryArangoImpl
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.networknt.rpc.router.RpcRouter
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  # registry all service handlers by from annotations
  - com.networknt.rpc.router.RpcStartupHookProvider
  # config event handle registration
  - com.networknt.eventuate.client.EventuateClientStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.ShutdownHookProvider:
  # - com.networknt.server.Test1ShutdownHook
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
- com.networknt.handler.MiddlewareHandler:
  # Exception Global exception handler that needs to be called first to wrap all middleware handlers and business handlers
  - com.networknt.exception.ExceptionHandler
  # Metrics handler to calculate response time accurately, this needs to be the second handler in the chain.
  - com.networknt.metrics.MetricsHandler
  # Traceability Put traceabilityId into response header from request header if it exists
  - com.networknt.traceability.TraceabilityHandler
  # Correlation Create correlationId if it doesn't exist in the request header and put it into the request header
  - com.networknt.correlation.CorrelationHandler
  # Jwt Token Verification for signature and expiration
  - com.networknt.rpc.security.JwtVerifyHandler
  # SimpleAudit Log important info about the request into audit log
  - com.networknt.audit.AuditHandler

# Individual service configuration

# light-codegen codegen-web interface implementations
- com.networknt.codegen.Generator:
  - com.networknt.codegen.rest.OpenApiGenerator
  - com.networknt.codegen.rest.SwaggerGenerator
  - com.networknt.codegen.hybrid.HybridServerGenerator
  - com.networknt.codegen.hybrid.HybridServiceGenerator
  - com.networknt.codegen.graphql.GraphqlGenerator
