# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasedocker
# new upgraded version. This needs to be changed for every release.
version: 1.5.29
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# skip checkout if you know all latest code has been checkout in the previous build
skip_checkout: false
# skip merge if develop branch has been merged to master. It is set to true as the previous
# release-maven task merged all repositories already. 
skip_merge: true
# skip maven build if you know the build has been done already
skip_maven: false
# skip release if it is already done.
skip_release: false
# skip docker publish if it is done already.
skip_docker: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  # here we checkout master branch to publish the images. 
  - branch: develop
    repository:
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/light-eventuate-4j.git
    - git@github.com:networknt/light-tram-kafka.git
    - git@github.com:networknt/light-tram-4j.git
    - git@github.com:networknt/light-example-4j.git
    # - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-docker.git
# merge develop to master for above repos
merge:
  - light-proxy
  - light-router
  - light-oauth2
  - light-tokenization
  - light-portal
  - light-eventuate-4j
  - light-tram-kafka
  - light-tram-4j
  - light-example-4j
  # - light-codegen
  # - light-docker
# maven build
maven:
  - light-proxy
  - light-router
  - light-oauth2
  - light-tokenization
  - light-portal
  - light-eventuate-4j
  - light-tram-kafka
  - light-tram-4j
  - light-example-4j/discovery/api_a/kubernetes
  - light-example-4j/discovery/api_b/kubernetes
  - light-example-4j/discovery/api_c/kubernetes
  - light-example-4j/discovery/api_d/kubernetes
  # - light-codegen

# update changelog in master, merge it to develop and publish to github.com
# please note that light-eventuate-4j and light-tram-4j are released in release-maven task.
release:
  - light-proxy
  - light-router
  - light-oauth2
  - light-tokenization
  - light-portal
  # - light-codegen

# build docker image and push to docker hub
docker:
  - light-proxy
  - light-router
  - light-oauth2/authorize
  - light-oauth2/client
  - light-oauth2/code
  - light-oauth2/key
  - light-oauth2/refresh-token
  - light-oauth2/service
  - light-oauth2/token
  - light-oauth2/user
  - light-tokenization
  - light-portal/hybrid-command
  - light-portal/hybrid-query
  - light-example-4j/discovery/api_a/kubernetes
  - light-example-4j/discovery/api_b/kubernetes
  - light-example-4j/discovery/api_c/kubernetes
  - light-example-4j/discovery/api_d/kubernetes
  # need to shutdown docker-compose-integration-test.yml before building the following two images.
  # moved to release-cdc sub task.
  # - light-eventuate-4j/eventuate-cdc-server
  # - light-tram-4j/tram-cdc-mysql-server
  # - light-docker/light-codegen
